export const STUDENT_LOG_IN = "STUDENT_LOG_IN";
export const COMPANY_LOG_IN = "COMPANY_LOG_IN";
export const STUDENT_SIGN_UP = "STUDENT_SIGN_UP";
export const STUDENT_GET_BASIC_DETAILS = "STUDENT_GET_BASIC_DETAILS";
export const STUDENT_UPDATE_BASIC_DETAILS = "STUDENT_UPDATE_BASIC_DETAILS";